<a href="https://colab.research.google.com/github/SubhadeepBhadra/fake-news-classifier-LSTM/blob/main/FakeNewsClassifierUsingLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('/content/drive/MyDrive/train.csv')

In [5]:
df.head()

,id,title,author,text,label
0,0,Congress Approves Annual Defense Budget,Daniel Martinez,A new study published in the peer-reviewed jou...,0
1,1,Senate Passes Bipartisan Infrastructure Package,Paul Anderson,The annual report released Thursday demonstrat...,0
2,2,Study Finds Mediterranean Diet Linked to Longe...,Steven Robinson,"In a press conference held Monday, spokesperso...",0
3,3,Vaccines Contain Nanobots That Track Your Loca...,RedPillReporter,"Wake up, sheeple! Hidden documents confirm tha...",1
4,4,Department of Labor Releases Monthly Jobs Report,Michael Torres,WASHINGTON — Officials confirmed Tuesday that ...,0

In [6]:
df.shape

(6000, 5)

In [7]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [8]:
###Drop Nan Values
df=df.dropna()

In [9]:
df.head()

,id,title,author,text,label
0,0,Congress Approves Annual Defense Budget,Daniel Martinez,A new study published in the peer-reviewed jou...,0
1,1,Senate Passes Bipartisan Infrastructure Package,Paul Anderson,The annual report released Thursday demonstrat...,0
2,2,Study Finds Mediterranean Diet Linked to Longe...,Steven Robinson,"In a press conference held Monday, spokesperso...",0
3,3,Vaccines Contain Nanobots That Track Your Loca...,RedPillReporter,"Wake up, sheeple! Hidden documents confirm tha...",1
4,4,Department of Labor Releases Monthly Jobs Report,Michael Torres,WASHINGTON — Officials confirmed Tuesday that ...,0

In [10]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [11]:
## Get the Dependent features
y=df['label']

In [12]:
X.shape

(6000, 4)

In [13]:
y.shape

(6000,)

In [14]:
import tensorflow as tf

In [15]:
tf.__version__

'2.19.0'

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [17]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [18]:
messages=X.copy()

In [19]:
messages['title'][1]

'Senate Passes Bipartisan Infrastructure Package'

In [20]:
messages

,id,title,author,text
0,0,Congress Approves Annual Defense Budget,Daniel Martinez,A new study published in the peer-reviewed jou...
1,1,Senate Passes Bipartisan Infrastructure Package,Paul Anderson,The annual report released Thursday demonstrat...
2,2,Study Finds Mediterranean Diet Linked to Longe...,Steven Robinson,"In a press conference held Monday, spokesperso..."
3,3,Vaccines Contain Nanobots That Track Your Loca...,RedPillReporter,"Wake up, sheeple! Hidden documents confirm tha..."
4,4,Department of Labor Releases Monthly Jobs Report,Michael Torres,WASHINGTON — Officials confirmed Tuesday that ...
...,...,...,...,...
5995,5995,Big Pharma Paying Doctors to Diagnose Healthy ...,UncensoredTruth,You won't believe what they are hiding! Source...
5996,5996,Big Pharma Paying Doctors to Diagnose Healthy ...,RealNewsNow,You won't believe what they are hiding! Source...
5997,5997,Hollywood Stars Running Satanic Cult Exposed b...,InsiderInformer,The mainstream media is REFUSING to cover the ...
5998,5998,Scientists CONFIRM: 5G Towers Spread New Virus,TruthSeeker99,"Wake up, sheeple! Hidden documents confirm tha..."
5999,5999,UN Security Council Discusses Peacekeeping Ope...,Daniel Martinez,The annual report released Thursday demonstrat...

In [21]:
#messages.reset_index(inplace=True)

In [22]:
messages

,id,title,author,text
0,0,Congress Approves Annual Defense Budget,Daniel Martinez,A new study published in the peer-reviewed jou...
1,1,Senate Passes Bipartisan Infrastructure Package,Paul Anderson,The annual report released Thursday demonstrat...
2,2,Study Finds Mediterranean Diet Linked to Longe...,Steven Robinson,"In a press conference held Monday, spokesperso..."
3,3,Vaccines Contain Nanobots That Track Your Loca...,RedPillReporter,"Wake up, sheeple! Hidden documents confirm tha..."
4,4,Department of Labor Releases Monthly Jobs Report,Michael Torres,WASHINGTON — Officials confirmed Tuesday that ...
...,...,...,...,...
5995,5995,Big Pharma Paying Doctors to Diagnose Healthy ...,UncensoredTruth,You won't believe what they are hiding! Source...
5996,5996,Big Pharma Paying Doctors to Diagnose Healthy ...,RealNewsNow,You won't believe what they are hiding! Source...
5997,5997,Hollywood Stars Running Satanic Cult Exposed b...,InsiderInformer,The mainstream media is REFUSING to cover the ...
5998,5998,Scientists CONFIRM: 5G Towers Spread New Virus,TruthSeeker99,"Wake up, sheeple! Hidden documents confirm tha..."
5999,5999,UN Security Council Discusses Peacekeeping Ope...,Daniel Martinez,The annual report released Thursday demonstrat...

In [23]:
import nltk
import re
from nltk.corpus import stopwords

In [24]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [25]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [26]:
corpus

['congress approv annual defens budget',
 'senat pass bipartisan infrastructur packag',
 'studi find mediterranean diet link longer life',
 'vaccin contain nanobot track locat',
 'depart labor releas monthli job report',
 'health offici urg flu vaccin winter',
 'leak document reveal moon land film hollywood',
 'report declin global malaria case',
 'presid sign new econom relief bill law',
 'citi council vote new public transit plan',
 'nasa success launch new mar explor rover',
 'govern releas annual budget propos',
 'scientist confirm discoveri new exoplanet',
 'scientist confirm discoveri new exoplanet',
 'scientist secretli replac sun giant lamp decad ago',
 'exclus presid secretli arrest bodi doubl run countri',
 'new smartphon app steal soul pastor warn',
 'new smartphon app steal soul pastor warn',
 'local water suppli lace fluorid dumb popul',
 'citi council vote new public transit plan',
 'local water suppli lace fluorid dumb popul',
 'local govern approv commun hous project',
 'astronom detect gravit wave black hole merger',
 'scientist confirm discoveri new exoplanet',
 'suprem court rule major privaci case',
 'presid sign new econom relief bill law',
 'govern hide cure cancer protect pharma profit',
 'secret underground citi built elit come collaps',
 'expos world leader plan secret popul cull',
 'stock market close higher econom data releas',
 'celebr death fake sourc claim',
 'auto industri report record electr vehicl sale',
 'local water suppli lace fluorid dumb popul',
 'citi council vote new public transit plan',
 'reveal elect result chang foreign satellit',
 'tech giant face antitrust scrutini regul',
 'new world order plan global currenc end year',
 'stock market close higher econom data releas',
 'world health organ releas annual health report',
 'scientist secretli replac sun giant lamp decad ago',
 'exclus presid secretli arrest bodi doubl run countri',
 'depart labor releas monthli job report',
 'scientist confirm discoveri new exoplanet',
 'proof climat chang hoax creat tech billionair',
 'govern releas annual budget propos',
 'break alien alreadi live among us whistleblow say',
 'ancient text prove earth year old scientist suppress',
 'health offici urg flu vaccin winter',
 'research publish find alzheim protein',
 'depart labor releas monthli job report',
 'scientist confirm g tower spread new viru',
 'govern releas annual budget propos',
 'citi council vote new public transit plan',
 'astronom detect gravit wave black hole merger',
 'reveal elect result chang foreign satellit',
 'reveal elect result chang foreign satellit',
 'break alien alreadi live among us whistleblow say',
 'vaccin contain nanobot track locat',
 'fbi whistleblow reveal deep state control major elect',
 'auto industri report record electr vehicl sale',
 'hollywood star run satan cult expos former member',
 'proof climat chang hoax creat tech billionair',
 'report declin global malaria case',
 'break alien alreadi live among us whistleblow say',
 'exclus presid secretli arrest bodi doubl run countri',
 'senat pass bipartisan infrastructur packag',
 'world health organ releas annual health report',
 'eat common food cure everi form cancer',
 'new world order plan global currenc end year',
 'fbi whistleblow reveal deep state control major elect',
 'attorney gener announc task forc cybercrim',
 'auto industri report record electr vehicl sale',
 'break famou athlet test posit android',
 'stock market close higher econom data releas',
 'pentagon secretli test mind control citizen',
 'scientist secretli replac sun giant lamp decad ago',
 'report declin global malaria case',
 'attorney gener announc task forc cybercrim',
 'new smartphon app steal soul pastor warn',
 'research publish find alzheim protein',
 'research publish find alzheim protein',
 'health offici urg flu vaccin winter',
 'exclus presid secretli arrest bodi doubl run countri',
 'citi council vote new public transit plan',
 'world health organ releas annual health report',
 'reveal elect result chang foreign satellit',
 'vaccin contain nanobot track locat',
 'intern treati nuclear prolifer extend',
 'leak document reveal moon land film hollywood',
 'tech giant face antitrust scrutini regul',
 'report declin global malaria case',
 'attorney gener announc task forc cybercrim',
 'citi council vote new public transit plan',
 'astronom detect gravit wave black hole merger',
 'shock tap water contain chemic lower iq',
 'world health organ releas annual health report',
 'stock market close higher econom data releas',
 'local govern approv commun hous project',
 'scientist develop new vaccin respiratori viru',
 'health offici urg flu vaccin winter',
 'feder reserv rais interest rate quarter point',
 'govern secretli put microchip drink water',
 'new world order plan global currenc end year',
 'reveal elect result chang foreign satellit',
 'un secur council discuss peacekeep oper',
 'big pharma pay doctor diagnos healthi peopl sick',
 'congress approv annual defens budget',
 'scientist secretli replac sun giant lamp decad ago',
 'nasa success launch new mar explor rover',
 'local water suppli lace fluorid dumb popul',
 'senat pass bipartisan infrastructur packag',
 'urgent new law ban privat gun ownership next month',
 'mainstream media confirm cia oper brainwash public',
 'intern treati nuclear prolifer extend',
 'local water suppli lace fluorid dumb popul',
 'world leader attend secret satan ritual everi year',
 'new smartphon app steal soul pastor warn',
 'new world order plan global currenc end year',
 'fbi whistleblow reveal deep state control major elect',
 'eat common food cure everi form cancer',
 'new world order plan global currenc end year',
 'break famou athlet test posit android',
 'citi council vote new public transit plan',
 'new smartphon app steal soul pastor warn',
 'chemtrail confirm mind control program insid',
 'new report show unemploy rate decad low',
 'pentagon secretli test mind control citizen',
 'senat pass bipartisan infrastructur packag',
 'feder reserv rais interest rate quarter point',
 'reveal elect result chang foreign satellit',
 'break famou athlet test posit android',
 'urgent new law ban privat gun ownership next month',
 'urgent new law ban privat gun ownership next month',
 'world leader attend secret satan ritual everi year',
 'vaccin contain nanobot track locat',
 'attorney gener announc task forc cybercrim',
 'suprem court rule major privaci case',
 'billionair control weather machin caus disast',
 'nasa success launch new mar explor rover',
 'secret underground citi built elit come collaps',
 'new report show unemploy rate decad low',
 'secret underground citi built elit come collaps',
 'urgent new law ban privat gun ownership next month',
 'auto industri report record electr vehicl sale',
 'govern hide cure cancer protect pharma profit',
 'attorney gener announc task forc cybercrim',
 'local govern approv commun hous project',
 'feder reserv rais interest rate quarter point',
 'citi council vote new public transit plan',
 'research publish find alzheim protein',
 'auto industri report record electr vehicl sale',
 'world health organ releas annual health report',
 'break alien alreadi live among us whistleblow say',
 'new environment regul take effect next month',
 'attorney gener announc task forc cybercrim',
 'scientist secretli replac sun giant lamp decad ago',
 'world leader attend secret satan ritual everi year',
 'expos world leader plan secret popul cull',
 'attorney gener announc task forc cybercrim',
 'urgent new law ban privat gun ownership next month',
 'un secur council discuss peacekeep oper',
 'scientist secretli replac sun giant lamp decad ago',
 'new world order plan global currenc end year',
 'big pharma pay doctor diagnos healthi peopl sick',
 'urgent new law ban privat gun ownership next month',
 'scientist develop new vaccin respiratori viru',
 'un secur council discuss peacekeep oper',
 'congress approv annual defens budget',
 'exclus presid secretli arrest bodi doubl run countri',
 'studi find mediterranean diet link longer life',
 'chemtrail confirm mind control program insid',
 'pentagon secretli test mind control citizen',
 'govern releas annual budget propos',
 'world leader attend secret satan ritual everi year',
 'leak document reveal moon land film hollywood',
 'astronom detect gravit wave black hole merger',
 'senat pass bipartisan infrastructur packag',
 'report declin global malaria case',
 'research publish find alzheim protein',
 'govern hide cure cancer protect pharma profit',
 'congress approv annual defens budget',
 'research publish find alzheim protein',
 'vaccin contain nanobot track locat',
 'break alien alreadi live among us whistleblow say',
 'shock tap water contain chemic lower iq',
 'climat summit reach agreement carbon emiss',
 'new world order plan global currenc end year',
 'local water suppli lace fluorid dumb popul',
 'un secur council discuss peacekeep oper',
 'climat summit reach agreement carbon emiss',
 'health offici urg flu vaccin winter',
 'nasa success launch new mar explor rover',
 'univers studi link sleep depriv heart risk',
 'feder reserv rais interest rate quarter point',
 'senat pass bipartisan infrastructur packag',
 'univers studi link sleep depriv heart risk',
 'nasa success launch new mar explor rover',
 'feder agenc issu guidelin ai use hire',
 'expos world leader plan secret popul cull',
 'auto industri report record electr vehicl sale',
 'proof climat chang hoax creat tech billionair',
 'govern secretli put microchip drink water',
 'scientist confirm g tower spread new viru',
 'pentagon secretli test mind control citizen',
 'tech giant face antitrust scrutini regul',
 'mainstream media confirm cia oper brainwash public',
 'urgent new law ban privat gun ownership next month',
 'report declin global malaria case',
 'pentagon secretli test mind control citizen',
 'hollywood star run satan cult expos former member',
 'congress approv annual defens budget',
 'stock market close higher econom data releas',
 'health offici urg flu vaccin winter',
 'expos world leader plan secret popul cull',
 'reveal elect result chang foreign satellit',
 'chemtrail confirm mind control program insid',
 'local govern approv commun hous project',
 'scientist confirm discoveri new exoplanet',
 'break famou athlet test posit android',
 'scientist confirm g tower spread new viru',
 'scientist develop new vaccin respiratori viru',
 'celebr death fake sourc claim',
 'new report show unemploy rate decad low',
 'world health organ releas annual health report',
 'astronom detect gravit wave black hole merger',
 'congress approv annual defens budget',
 'shock tap water contain chemic lower iq',
 'local govern approv commun hous project',
 'shock tap water contain chemic lower iq',
 'govern hide cure cancer protect pharma profit',
 'vaccin contain nanobot track locat',
 'nasa success launch new mar explor rover',
 'expos world leader plan secret popul cull',
 'univers studi link sleep depriv heart risk',
 'depart labor releas monthli job report',
 'nasa success launch new mar explor rover',
 'vaccin contain nanobot track locat',
 'shock tap water contain chemic lower iq',
 'feder agenc issu guidelin ai use hire',
 'govern releas annual budget propos',
 'local water suppli lace fluorid dumb popul',
 'scientist develop new vaccin respiratori viru',
 'scientist secretli replac sun giant lamp decad ago',
 'intern treati nuclear prolifer extend',
 'nasa success launch new mar explor rover',
 'presid sign new econom relief bill law',
 'suprem court rule major privaci case',
 'feder reserv rais interest rate quarter point',
 'local water suppli lace fluorid dumb popul',
 'reveal elect result chang foreign satellit',
 'un secur council discuss peacekeep oper',
 'world health organ releas annual health report',
 'urgent new law ban privat gun ownership next month',
 'chemtrail confirm mind control program insid',
 'un secur council discuss peacekeep oper',
 'un secur council discuss peacekeep oper',
 'exclus presid secretli arrest bodi doubl run countri',
 'health offici urg flu vaccin winter',
 'nasa success launch new mar explor rover',
 'congress approv annual defens budget',
 'health offici urg flu vaccin winter',
 'scientist confirm g tower spread new viru',
 'urgent new law ban privat gun ownership next month',
 'report declin global malaria case',
 'new environment regul take effect next month',
 'senat pass bipartisan infrastructur packag',
 'expos world leader plan secret popul cull',
 'pentagon secretli test mind control citizen',
 'senat pass bipartisan infrastructur packag',
 'eat common food cure everi form cancer',
 'ancient text prove earth year old scientist suppress',
 'billionair control weather machin caus disast',
 'big pharma pay doctor diagnos healthi peopl sick',
 'expos world leader plan secret popul cull',
 'studi find mediterranean diet link longer life',
 'scientist confirm g tower spread new viru',
 'billionair control weather machin caus disast',
 'feder reserv chair testifi senat committe',
 'scientist confirm discoveri new exoplanet',
 'secret underground citi built elit come collaps',
 'celebr death fake sourc claim',
 'billionair control weather machin caus disast',
 'senat pass bipartisan infrastructur packag',
 'fbi whistleblow reveal deep state control major elect',
 'secret underground citi built elit come collaps',
 'ancient text prove earth year old scientist suppress',
 'billionair control weather machin caus disast',
 'eat common food cure everi form cancer',
 'expos world leader plan secret popul cull',
 'expos world leader plan secret popul cull',
 'reveal elect result chang foreign satellit',
 'chemtrail confirm mind control program insid',
 'new smartphon app steal soul pastor warn',
 'shock tap water contain chemic lower iq',
 'reveal elect result chang foreign satellit',
 'vaccin contain nanobot track locat',
 'break famou athlet test posit android',
 'scientist confirm g tower spread new viru',
 'citi council vote new public transit plan',
 'pentagon secretli test mind control citizen',
 'intern treati nuclear prolifer extend',
 'shock tap water contain chemic lower iq',
 'doctor warn common medic turn peopl zombi',
 'scientist confirm discoveri new exoplanet',
 'billionair control weather machin caus disast',
 'govern secretli put microchip drink water',
 'feder reserv rais interest rate quarter point',
 'doctor warn common medic turn peopl zombi',
 'depart labor releas monthli job report',
 'urgent new law ban privat gun ownership next month',
 'mainstream media confirm cia oper brainwash public',
 'senat pass bipartisan infrastructur packag',
 'local govern approv commun hous project',
 'secret underground citi built elit come collaps',
 'congress approv annual defens budget',
 'attorney gener announc task forc cybercrim',
 'billionair control weather machin caus disast',
 'scientist confirm discoveri new exoplanet',
 'chemtrail confirm mind control program insid',
 'new environment regul take effect next month',
 'intern treati nuclear prolifer extend',
 'exclus presid secretli arrest bodi doubl run countri',
 'celebr death fake sourc claim',
 'feder reserv chair testifi senat committe',
 'univers studi link sleep depriv heart risk',
 'break famou athlet test posit android',
 'new world order plan global currenc end year',
 'feder reserv chair testifi senat committe',
 'feder reserv chair testifi senat committe',
 'tech giant face antitrust scrutini regul',
 'suprem court rule major privaci case',
 'health offici urg flu vaccin winter',
 'scientist secretli replac sun giant lamp decad ago',
 'scientist develop new vaccin respiratori viru',
 'new smartphon app steal soul pastor warn',
 'suprem court rule major privaci case',
 'pentagon secretli test mind control citizen',
 'un secur council discuss peacekeep oper',
 'new smartphon app steal soul pastor warn',
 'new smartphon app steal soul pastor warn',
 'feder reserv chair testifi senat committe',
 'climat summit reach agreement carbon emiss',
 'reveal elect result chang foreign satellit',
 'suprem court rule major privaci case',
 'scientist confirm discoveri new exoplanet',
 'senat pass bipartisan infrastructur packag',
 'leak document reveal moon land film hollywood',
 'feder reserv rais interest rate quarter point',
 'feder reserv chair testifi senat committe',
 'congress approv annual defens budget',
 'billionair control weather machin caus disast',
 'ancient text prove earth year old scientist suppress',
 'govern releas annual budget propos',
 'scientist confirm discoveri new exoplanet',
 'govern releas annual budget propos',
 'billionair control weather machin caus disast',
 'celebr death fake sourc claim',
 'nasa success launch new mar explor rover',
 'fbi whistleblow reveal deep state control major elect',
 'research publish find alzheim protein',
 'break alien alreadi live among us whistleblow say',
 'big pharma pay doctor diagnos healthi peopl sick',
 'scientist secretli replac sun giant lamp decad ago',
 'local water suppli lace fluorid dumb popul',
 'congress approv annual defens budget',
 'scientist confirm discoveri new exoplanet',
 'govern secretli put microchip drink water',
 'astronom detect gravit wave black hole merger',
 'new report show unemploy rate decad low',
 'auto industri report record electr vehicl sale',
 'report declin global malaria case',
 'govern hide cure cancer protect pharma profit',
 'fbi whistleblow reveal deep state control major elect',
 'scientist confirm discoveri new exoplanet',
 'shock tap water contain chemic lower iq',
 'scientist secretli replac sun giant lamp decad ago',
 'senat pass bipartisan infrastructur packag',
 'eat common food cure everi form cancer',
 'scientist develop new vaccin respiratori viru',
 'new report show unemploy rate decad low',
 'shock tap water contain chemic lower iq',
 'tech giant face antitrust scrutini regul',
 'astronom detect gravit wave black hole merger',
 'expos world leader plan secret popul cull',
 'un secur council discuss peacekeep oper',
 'depart labor releas monthli job report',
 'secret underground citi built elit come collaps',
 'expos world leader plan secret popul cull',
 'scientist develop new vaccin respiratori viru',
 'astronom detect gravit wave black hole merger',
 'leak document reveal moon land film hollywood',
 'break famou athlet test posit android',
 'hollywood star run satan cult expos former member',
 'fbi whistleblow reveal deep state control major elect',
 'nasa success launch new mar explor rover',
 'govern hide cure cancer protect pharma profit',
 'mainstream media confirm cia oper brainwash public',
 'un secur council discuss peacekeep oper',
 'auto industri report record electr vehicl sale',
 'research publish find alzheim protein',
 'leak document reveal moon land film hollywood',
 'new smartphon app steal soul pastor warn',
 'local water suppli lace fluorid dumb popul',
 'local govern approv commun hous project',
 'shock tap water contain chemic lower iq',
 'astronom detect gravit wave black hole merger',
 'feder agenc issu guidelin ai use hire',
 'nasa success launch new mar explor rover',
 'new environment regul take effect next month',
 'break famou athlet test posit android',
 'new environment regul take effect next month',
 'chemtrail confirm mind control program insid',
 'intern treati nuclear prolifer extend',
 'un secur council discuss peacekeep oper',
 'vaccin contain nanobot track locat',
 'citi council vote new public transit plan',
 'report declin global malaria case',
 'world leader attend secret satan ritual everi year',
 'new report show unemploy rate decad low',
 'stock market close higher econom data releas',
 'health offici urg flu vaccin winter',
 'feder reserv rais interest rate quarter point',
 'fbi whistleblow reveal deep state control major elect',
 'scientist develop new vaccin respiratori viru',
 'celebr death fake sourc claim',

In [27]:
corpus[1]

'senat pass bipartisan infrastructur packag'

In [28]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[3426, 4469, 4823, 4171, 1811],
 [2005, 3248, 3496, 2464, 3926],
 [3421, 3562, 217, 3466, 932, 2506, 4698],
 [4003, 798, 1647, 1968, 3571],
 [3200, 2678, 1776, 4658, 1882, 2659],
 [2199, 959, 3241, 3510, 4003, 721],
 [3573, 4511, 4549, 3066, 2031, 2954, 4559],
 [2659, 2585, 4900, 66, 4057],
 [1408, 3758, 2706, 4336, 4062, 4413, 4435],
 [1222, 1745, 2150, 2706, 1828, 3054, 2045],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [429, 1776, 4823, 1811, 2423],
 [4555, 141, 2215, 2706, 498],
 [4555, 141, 2215, 2706, 498],
 [4555, 2102, 1163, 4590, 2121, 1714, 1198, 1772],
 [458, 1408, 2102, 961, 3999, 4806, 663, 3556],
 [2706, 132, 2029, 735, 732, 540, 511],
 [2706, 132, 2029, 735, 732, 540, 511],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [1222, 1745, 2150, 2706, 1828, 3054, 2045],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [1843, 429, 4469, 2015, 4040, 2653],
 [2783, 4845, 2242, 1263, 2727, 3417, 2397],
 [4555, 141, 2215, 2706, 498],
 [3150, 1377, 2943, 762, 3667, 4057],
 [1408, 3758, 2706, 4336, 4062, 4413, 4435],
 [429, 3617, 2411, 4675, 2365, 4835, 4008],
 [4662, 1915, 1222, 4652, 4746, 3995, 4014],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [4719, 2849, 4869, 4638, 4336, 3819, 1776],
 [748, 1773, 1094, 4711, 4554],
 [497, 4908, 2659, 4848, 1127, 2938, 4436],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [1222, 1745, 2150, 2706, 1828, 3054, 2045],
 [4549, 3713, 3417, 1444, 4905, 3259],
 [1890, 2121, 4984, 400, 2769, 2529],
 [2706, 4074, 132, 2045, 4900, 2680, 3465, 2464],
 [4719, 2849, 4869, 4638, 4336, 3819, 1776],
 [4074, 2199, 3042, 1776, 4823, 2199, 2659],
 [4555, 2102, 1163, 4590, 2121, 1714, 1198, 1772],
 [458, 1408, 2102, 961, 3999, 4806, 663, 3556],
 [3200, 2678, 1776, 4658, 1882, 2659],
 [4555, 141, 2215, 2706, 498],
 [406, 3405, 1444, 3627, 2061, 1890, 1534],
 [429, 1776, 4823, 1811, 2423],
 [2349, 3088, 1767, 1496, 2403, 3313, 880, 927],
 [624, 4547, 4833, 3332, 2464, 3788, 4555, 4884],
 [2199, 959, 3241, 3510, 4003, 721],
 [3933, 848, 3562, 1895, 4933],
 [3200, 2678, 1776, 4658, 1882, 2659],
 [4555, 141, 3045, 4038, 3727, 2706, 1173],
 [429, 1776, 4823, 1811, 2423],
 [1222, 1745, 2150, 2706, 1828, 3054, 2045],
 [2783, 4845, 2242, 1263, 2727, 3417, 2397],
 [4549, 3713, 3417, 1444, 4905, 3259],
 [4549, 3713, 3417, 1444, 4905, 3259],
 [2349, 3088, 1767, 1496, 2403, 3313, 880, 927],
 [4003, 798, 1647, 1968, 3571],
 [1132, 880, 4549, 2960, 3085, 3017, 762, 3713],
 [497, 4908, 2659, 4848, 1127, 2938, 4436],
 [4559, 2841, 663, 4006, 25, 852, 2948, 3134],
 [406, 3405, 1444, 3627, 2061, 1890, 1534],
 [2659, 2585, 4900, 66, 4057],
 [2349, 3088, 1767, 1496, 2403, 3313, 880, 927],
 [458, 1408, 2102, 961, 3999, 4806, 663, 3556],
 [2005, 3248, 3496, 2464, 3926],
 [4074, 2199, 3042, 1776, 4823, 2199, 2659],
 [712, 705, 3079, 2411, 1607, 2496, 4675],
 [2706, 4074, 132, 2045, 4900, 2680, 3465, 2464],
 [1132, 880, 4549, 2960, 3085, 3017, 762, 3713],
 [3526, 446, 216, 4803, 3474, 2215],
 [497, 4908, 2659, 4848, 1127, 2938, 4436],
 [2349, 4058, 317, 3422, 478, 4809],
 [4719, 2849, 4869, 4638, 4336, 3819, 1776],
 [1268, 2102, 3422, 1438, 3017, 3768],
 [4555, 2102, 1163, 4590, 2121, 1714, 1198, 1772],
 [2659, 2585, 4900, 66, 4057],
 [3526, 446, 216, 4803, 3474, 2215],
 [2706, 132, 2029, 735, 732, 540, 511],
 [3933, 848, 3562, 1895, 4933],
 [3933, 848, 3562, 1895, 4933],
 [2199, 959, 3241, 3510, 4003, 721],
 [458, 1408, 2102, 961, 3999, 4806, 663, 3556],
 [1222, 1745, 2150, 2706, 1828, 3054, 2045],
 [4074, 2199, 3042, 1776, 4823, 2199, 2659],
 [4549, 3713, 3417, 1444, 4905, 3259],
 [4003, 798, 1647, 1968, 3571],
 [3178, 3520, 3513, 102, 4651],
 [3573, 4511, 4549, 3066, 2031, 2954, 4559],
 [1890, 2121, 4984, 400, 2769, 2529],
 [2659, 2585, 4900, 66, 4057],
 [3526, 446, 216, 4803, 3474, 2215],
 [1222, 1745, 2150, 2706, 1828, 3054, 2045],
 [2783, 4845, 2242, 1263, 2727, 3417, 2397],
 [471, 4427, 3812, 798, 4516, 4794, 1919],
 [4074, 2199, 3042, 1776, 4823, 2199, 2659],
 [4719, 2849, 4869, 4638, 4336, 3819, 1776],
 [1843, 429, 4469, 2015, 4040, 2653],
 [4555, 918, 2706, 4003, 3625, 1173],
 [2199, 959, 3241, 3510, 4003, 721],
 [4845, 3300, 38, 3992, 2775, 1902, 4773],
 [429, 2102, 894, 4122, 3769, 3812],
 [2706, 4074, 132, 2045, 4900, 2680, 3465, 2464],
 [4549, 3713, 3417, 1444, 4905, 3259],
 [4041, 4430, 1745, 462, 2367, 3752],
 [2222, 4835, 4483, 4292, 170, 2398, 4176, 3368],
 [3426, 4469, 4823, 4171, 1811],
 [4555, 2102, 1163, 4590, 2121, 1714, 1198, 1772],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [2005, 3248, 3496, 2464, 3926],
 [2535, 2706, 4435, 1927, 1722, 2528, 24, 3628, 2071],
 [1718, 3643, 141, 4880, 3752, 415, 1828],
 [3178, 3520, 3513, 102, 4651],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [4074, 4492, 882, 4662, 4006, 4395, 1607, 2464],
 [2706, 132, 2029, 735, 732, 540, 511],
 [2706, 4074, 132, 2045, 4900, 2680, 3465, 2464],
 [1132, 880, 4549, 2960, 3085, 3017, 762, 3713],
 [712, 705, 3079, 2411, 1607, 2496, 4675],
 [2706, 4074, 132, 2045, 4900, 2680, 3465, 2464],
 [2349, 4058, 317, 3422, 478, 4809],
 [1222, 1745, 2150, 2706, 1828, 3054, 2045],
 [2706, 132, 2029, 735, 732, 540, 511],
 [3832, 141, 1438, 3017, 2223, 4867],
 [2706, 2659, 2894, 4583, 2775, 1198, 4847],
 [1268, 2102, 3422, 1438, 3017, 3768],
 [2005, 3248, 3496, 2464, 3926],
 [4845, 3300, 38, 3992, 2775, 1902, 4773],
 [4549, 3713, 3417, 1444, 4905, 3259],
 [2349, 4058, 317, 3422, 478, 4809],
 [2535, 2706, 4435, 1927, 1722, 2528, 24, 3628, 2071],
 [2535, 2706, 4435, 1927, 1722, 2528, 24, 3628, 2071],
 [4074, 4492, 882, 4662, 4006, 4395, 1607, 2464],
 [4003, 798, 1647, 1968, 3571],
 [3526, 446, 216, 4803, 3474, 2215],
 [3150, 1377, 2943, 762, 3667, 4057],
 [1534, 3017, 2912, 1433, 4691, 916],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [4662, 1915, 1222, 4652, 4746, 3995, 4014],
 [2706, 2659, 2894, 4583, 2775, 1198, 4847],
 [4662, 1915, 1222, 4652, 4746, 3995, 4014],
 [2535, 2706, 4435, 1927, 1722, 2528, 24, 3628, 2071],
 [497, 4908, 2659, 4848, 1127, 2938, 4436],
 [429, 3617, 2411, 4675, 2365, 4835, 4008],
 [3526, 446, 216, 4803, 3474, 2215],
 [1843, 429, 4469, 2015, 4040, 2653],
 [4845, 3300, 38, 3992, 2775, 1902, 4773],
 [1222, 1745, 2150, 2706, 1828, 3054, 2045],
 [3933, 848, 3562, 1895, 4933],
 [497, 4908, 2659, 4848, 1127, 2938, 4436],
 [4074, 2199, 3042, 1776, 4823, 2199, 2659],
 [2349, 3088, 1767, 1496, 2403, 3313, 880, 927],
 [2706, 4058, 2529, 1067, 2624, 3628, 2071],
 [3526, 446, 216, 4803, 3474, 2215],
 [4555, 2102, 1163, 4590, 2121, 1714, 1198, 1772],
 [4074, 4492, 882, 4662, 4006, 4395, 1607, 2464],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [3526, 446, 216, 4803, 3474, 2215],
 [2535, 2706, 4435, 1927, 1722, 2528, 24, 3628, 2071],
 [4041, 4430, 1745, 462, 2367, 3752],
 [4555, 2102, 1163, 4590, 2121, 1714, 1198, 1772],
 [2706, 4074, 132, 2045, 4900, 2680, 3465, 2464],
 [2222, 4835, 4483, 4292, 170, 2398, 4176, 3368],
 [2535, 2706, 4435, 1927, 1722, 2528, 24, 3628, 2071],
 [4555, 918, 2706, 4003, 3625, 1173],
 [4041, 4430, 1745, 462, 2367, 3752],
 [3426, 4469, 4823, 4171, 1811],
 [458, 1408, 2102, 961, 3999, 4806, 663, 3556],
 [3421, 3562, 217, 3466, 932, 2506, 4698],
 [3832, 141, 1438, 3017, 2223, 4867],
 [1268, 2102, 3422, 1438, 3017, 3768],
 [429, 1776, 4823, 1811, 2423],
 [4074, 4492, 882, 4662, 4006, 4395, 1607, 2464],
 [3573, 4511, 4549, 3066, 2031, 2954, 4559],
 [2783, 4845, 2242, 1263, 2727, 3417, 2397],
 [2005, 3248, 3496, 2464, 3926],
 [2659, 2585, 4900, 66, 4057],
 [3933, 848, 3562, 1895, 4933],
 [429, 3617, 2411, 4675, 2365, 4835, 4008],
 [3426, 4469, 4823, 4171, 1811],
 [3933, 848, 3562, 1895, 4933],
 [4003, 798, 1647, 1968, 3571],
 [2349, 3088, 1767, 1496, 2403, 3313, 880, 927],
 [471, 4427, 3812, 798, 4516, 4794, 1919],
 [3405, 660, 856, 1445, 3583, 4455],
 [2706, 4074, 132, 2045, 4900, 2680, 3465, 2464],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [4041, 4430, 1745, 462, 2367, 3752],
 [3405, 660, 856, 1445, 3583, 4455],
 [2199, 959, 3241, 3510, 4003, 721],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [3401, 3421, 932, 4397, 1496, 3426, 497],
 [4845, 3300, 38, 3992, 2775, 1902, 4773],
 [2005, 3248, 3496, 2464, 3926],
 [3401, 3421, 932, 4397, 1496, 3426, 497],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [4845, 1509, 2846, 4983, 4685, 3347, 948],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [497, 4908, 2659, 4848, 1127, 2938, 4436],
 [406, 3405, 1444, 3627, 2061, 1890, 1534],
 [429, 2102, 894, 4122, 3769, 3812],
 [4555, 141, 3045, 4038, 3727, 2706, 1173],
 [1268, 2102, 3422, 1438, 3017, 3768],
 [1890, 2121, 4984, 400, 2769, 2529],
 [1718, 3643, 141, 4880, 3752, 415, 1828],
 [2535, 2706, 4435, 1927, 1722, 2528, 24, 3628, 2071],
 [2659, 2585, 4900, 66, 4057],
 [1268, 2102, 3422, 1438, 3017, 3768],
 [4559, 2841, 663, 4006, 25, 852, 2948, 3134],
 [3426, 4469, 4823, 4171, 1811],
 [4719, 2849, 4869, 4638, 4336, 3819, 1776],
 [2199, 959, 3241, 3510, 4003, 721],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [4549, 3713, 3417, 1444, 4905, 3259],
 [3832, 141, 1438, 3017, 2223, 4867],
 [1843, 429, 4469, 2015, 4040, 2653],
 [4555, 141, 2215, 2706, 498],
 [2349, 4058, 317, 3422, 478, 4809],
 [4555, 141, 3045, 4038, 3727, 2706, 1173],
 [4555, 918, 2706, 4003, 3625, 1173],
 [748, 1773, 1094, 4711, 4554],
 [2706, 2659, 2894, 4583, 2775, 1198, 4847],
 [4074, 2199, 3042, 1776, 4823, 2199, 2659],
 [2783, 4845, 2242, 1263, 2727, 3417, 2397],
 [3426, 4469, 4823, 4171, 1811],
 [471, 4427, 3812, 798, 4516, 4794, 1919],
 [1843, 429, 4469, 2015, 4040, 2653],
 [471, 4427, 3812, 798, 4516, 4794, 1919],
 [429, 3617, 2411, 4675, 2365, 4835, 4008],
 [4003, 798, 1647, 1968, 3571],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [3401, 3421, 932, 4397, 1496, 3426, 497],
 [3200, 2678, 1776, 4658, 1882, 2659],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [4003, 798, 1647, 1968, 3571],
 [471, 4427, 3812, 798, 4516, 4794, 1919],
 [4845, 1509, 2846, 4983, 4685, 3347, 948],
 [429, 1776, 4823, 1811, 2423],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [4555, 918, 2706, 4003, 3625, 1173],
 [4555, 2102, 1163, 4590, 2121, 1714, 1198, 1772],
 [3178, 3520, 3513, 102, 4651],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [1408, 3758, 2706, 4336, 4062, 4413, 4435],
 [3150, 1377, 2943, 762, 3667, 4057],
 [4845, 3300, 38, 3992, 2775, 1902, 4773],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [4549, 3713, 3417, 1444, 4905, 3259],
 [4041, 4430, 1745, 462, 2367, 3752],
 [4074, 2199, 3042, 1776, 4823, 2199, 2659],
 [2535, 2706, 4435, 1927, 1722, 2528, 24, 3628, 2071],
 [3832, 141, 1438, 3017, 2223, 4867],
 [4041, 4430, 1745, 462, 2367, 3752],
 [4041, 4430, 1745, 462, 2367, 3752],
 [458, 1408, 2102, 961, 3999, 4806, 663, 3556],
 [2199, 959, 3241, 3510, 4003, 721],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [3426, 4469, 4823, 4171, 1811],
 [2199, 959, 3241, 3510, 4003, 721],
 [4555, 141, 3045, 4038, 3727, 2706, 1173],
 [2535, 2706, 4435, 1927, 1722, 2528, 24, 3628, 2071],
 [2659, 2585, 4900, 66, 4057],
 [2706, 4058, 2529, 1067, 2624, 3628, 2071],
 [2005, 3248, 3496, 2464, 3926],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [1268, 2102, 3422, 1438, 3017, 3768],
 [2005, 3248, 3496, 2464, 3926],
 [712, 705, 3079, 2411, 1607, 2496, 4675],
 [624, 4547, 4833, 3332, 2464, 3788, 4555, 4884],
 [1534, 3017, 2912, 1433, 4691, 916],
 [2222, 4835, 4483, 4292, 170, 2398, 4176, 3368],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [3421, 3562, 217, 3466, 932, 2506, 4698],
 [4555, 141, 3045, 4038, 3727, 2706, 1173],
 [1534, 3017, 2912, 1433, 4691, 916],
 [4845, 3300, 1501, 3408, 2005, 863],
 [4555, 141, 2215, 2706, 498],
 [4662, 1915, 1222, 4652, 4746, 3995, 4014],
 [748, 1773, 1094, 4711, 4554],
 [1534, 3017, 2912, 1433, 4691, 916],
 [2005, 3248, 3496, 2464, 3926],
 [1132, 880, 4549, 2960, 3085, 3017, 762, 3713],
 [4662, 1915, 1222, 4652, 4746, 3995, 4014],
 [624, 4547, 4833, 3332, 2464, 3788, 4555, 4884],
 [1534, 3017, 2912, 1433, 4691, 916],
 [712, 705, 3079, 2411, 1607, 2496, 4675],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [4549, 3713, 3417, 1444, 4905, 3259],
 [3832, 141, 1438, 3017, 2223, 4867],
 [2706, 132, 2029, 735, 732, 540, 511],
 [471, 4427, 3812, 798, 4516, 4794, 1919],
 [4549, 3713, 3417, 1444, 4905, 3259],
 [4003, 798, 1647, 1968, 3571],
 [2349, 4058, 317, 3422, 478, 4809],
 [4555, 141, 3045, 4038, 3727, 2706, 1173],
 [1222, 1745, 2150, 2706, 1828, 3054, 2045],
 [1268, 2102, 3422, 1438, 3017, 3768],
 [3178, 3520, 3513, 102, 4651],
 [471, 4427, 3812, 798, 4516, 4794, 1919],
 [4292, 511, 705, 3538, 1696, 4176, 2900],
 [4555, 141, 2215, 2706, 498],
 [1534, 3017, 2912, 1433, 4691, 916],
 [429, 2102, 894, 4122, 3769, 3812],
 [4845, 3300, 38, 3992, 2775, 1902, 4773],
 [4292, 511, 705, 3538, 1696, 4176, 2900],
 [3200, 2678, 1776, 4658, 1882, 2659],
 [2535, 2706, 4435, 1927, 1722, 2528, 24, 3628, 2071],
 [1718, 3643, 141, 4880, 3752, 415, 1828],
 [2005, 3248, 3496, 2464, 3926],
 [1843, 429, 4469, 2015, 4040, 2653],
 [4662, 1915, 1222, 4652, 4746, 3995, 4014],
 [3426, 4469, 4823, 4171, 1811],
 [3526, 446, 216, 4803, 3474, 2215],
 [1534, 3017, 2912, 1433, 4691, 916],
 [4555, 141, 2215, 2706, 498],
 [3832, 141, 1438, 3017, 2223, 4867],
 [2706, 4058, 2529, 1067, 2624, 3628, 2071],
 [3178, 3520, 3513, 102, 4651],
 [458, 1408, 2102, 961, 3999, 4806, 663, 3556],
 [748, 1773, 1094, 4711, 4554],
 [4845, 3300, 1501, 3408, 2005, 863],
 [3401, 3421, 932, 4397, 1496, 3426, 497],
 [2349, 4058, 317, 3422, 478, 4809],
 [2706, 4074, 132, 2045, 4900, 2680, 3465, 2464],
 [4845, 3300, 1501, 3408, 2005, 863],
 [4845, 3300, 1501, 3408, 2005, 863],
 [1890, 2121, 4984, 400, 2769, 2529],
 [3150, 1377, 2943, 762, 3667, 4057],
 [2199, 959, 3241, 3510, 4003, 721],
 [4555, 2102, 1163, 4590, 2121, 1714, 1198, 1772],
 [4555, 918, 2706, 4003, 3625, 1173],
 [2706, 132, 2029, 735, 732, 540, 511],
 [3150, 1377, 2943, 762, 3667, 4057],
 [1268, 2102, 3422, 1438, 3017, 3768],
 [4041, 4430, 1745, 462, 2367, 3752],
 [2706, 132, 2029, 735, 732, 540, 511],
 [2706, 132, 2029, 735, 732, 540, 511],
 [4845, 3300, 1501, 3408, 2005, 863],
 [3405, 660, 856, 1445, 3583, 4455],
 [4549, 3713, 3417, 1444, 4905, 3259],
 [3150, 1377, 2943, 762, 3667, 4057],
 [4555, 141, 2215, 2706, 498],
 [2005, 3248, 3496, 2464, 3926],
 [3573, 4511, 4549, 3066, 2031, 2954, 4559],
 [4845, 3300, 38, 3992, 2775, 1902, 4773],
 [4845, 3300, 1501, 3408, 2005, 863],
 [3426, 4469, 4823, 4171, 1811],
 [1534, 3017, 2912, 1433, 4691, 916],
 [624, 4547, 4833, 3332, 2464, 3788, 4555, 4884],
 [429, 1776, 4823, 1811, 2423],
 [4555, 141, 2215, 2706, 498],
 [429, 1776, 4823, 1811, 2423],
 [1534, 3017, 2912, 1433, 4691, 916],
 [748, 1773, 1094, 4711, 4554],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [1132, 880, 4549, 2960, 3085, 3017, 762, 3713],
 [3933, 848, 3562, 1895, 4933],
 [2349, 3088, 1767, 1496, 2403, 3313, 880, 927],
 [2222, 4835, 4483, 4292, 170, 2398, 4176, 3368],
 [4555, 2102, 1163, 4590, 2121, 1714, 1198, 1772],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [3426, 4469, 4823, 4171, 1811],
 [4555, 141, 2215, 2706, 498],
 [429, 2102, 894, 4122, 3769, 3812],
 [2783, 4845, 2242, 1263, 2727, 3417, 2397],
 [2706, 2659, 2894, 4583, 2775, 1198, 4847],
 [497, 4908, 2659, 4848, 1127, 2938, 4436],
 [2659, 2585, 4900, 66, 4057],
 [429, 3617, 2411, 4675, 2365, 4835, 4008],
 [1132, 880, 4549, 2960, 3085, 3017, 762, 3713],
 [4555, 141, 2215, 2706, 498],
 [471, 4427, 3812, 798, 4516, 4794, 1919],
 [4555, 2102, 1163, 4590, 2121, 1714, 1198, 1772],
 [2005, 3248, 3496, 2464, 3926],
 [712, 705, 3079, 2411, 1607, 2496, 4675],
 [4555, 918, 2706, 4003, 3625, 1173],
 [2706, 2659, 2894, 4583, 2775, 1198, 4847],
 [471, 4427, 3812, 798, 4516, 4794, 1919],
 [1890, 2121, 4984, 400, 2769, 2529],
 [2783, 4845, 2242, 1263, 2727, 3417, 2397],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [4041, 4430, 1745, 462, 2367, 3752],
 [3200, 2678, 1776, 4658, 1882, 2659],
 [4662, 1915, 1222, 4652, 4746, 3995, 4014],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [4555, 918, 2706, 4003, 3625, 1173],
 [2783, 4845, 2242, 1263, 2727, 3417, 2397],
 [3573, 4511, 4549, 3066, 2031, 2954, 4559],
 [2349, 4058, 317, 3422, 478, 4809],
 [4559, 2841, 663, 4006, 25, 852, 2948, 3134],
 [1132, 880, 4549, 2960, 3085, 3017, 762, 3713],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [429, 3617, 2411, 4675, 2365, 4835, 4008],
 [1718, 3643, 141, 4880, 3752, 415, 1828],
 [4041, 4430, 1745, 462, 2367, 3752],
 [497, 4908, 2659, 4848, 1127, 2938, 4436],
 [3933, 848, 3562, 1895, 4933],
 [3573, 4511, 4549, 3066, 2031, 2954, 4559],
 [2706, 132, 2029, 735, 732, 540, 511],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [1843, 429, 4469, 2015, 4040, 2653],
 [471, 4427, 3812, 798, 4516, 4794, 1919],
 [2783, 4845, 2242, 1263, 2727, 3417, 2397],
 [4845, 1509, 2846, 4983, 4685, 3347, 948],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [2706, 4058, 2529, 1067, 2624, 3628, 2071],
 [2349, 4058, 317, 3422, 478, 4809],
 [2706, 4058, 2529, 1067, 2624, 3628, 2071],
 [3832, 141, 1438, 3017, 2223, 4867],
 [3178, 3520, 3513, 102, 4651],
 [4041, 4430, 1745, 462, 2367, 3752],
 [4003, 798, 1647, 1968, 3571],
 [1222, 1745, 2150, 2706, 1828, 3054, 2045],
 [2659, 2585, 4900, 66, 4057],
 [4074, 4492, 882, 4662, 4006, 4395, 1607, 2464],
 [2706, 2659, 2894, 4583, 2775, 1198, 4847],
 [4719, 2849, 4869, 4638, 4336, 3819, 1776],
 [2199, 959, 3241, 3510, 4003, 721],
 [4845, 3300, 38, 3992, 2775, 1902, 4773],
 [1132, 880, 4549, 2960, 3085, 3017, 762, 3713],
 [4555, 918, 2706, 4003, 3625, 1173],
 [748, 1773, 1094, 4711, 4554],
 [429, 2102, 894, 4122, 3769, 3812],
 [624, 4547, 4833, 3332, 2464, 3788, 4555, 4884],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [1222, 1745, 2150, 2706, 1828, 3054, 2045],
 [4555, 918, 2706, 4003, 3625, 1173],
 [3573, 4511, 4549, 3066, 2031, 2954, 4559],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [1132, 880, 4549, 2960, 3085, 3017, 762, 3713],
 [2659, 2585, 4900, 66, 4057],
 [3150, 1377, 2943, 762, 3667, 4057],
 [4292, 511, 705, 3538, 1696, 4176, 2900],
 [2349, 3088, 1767, 1496, 2403, 3313, 880, 927],
 [2783, 4845, 2242, 1263, 2727, 3417, 2397],
 [624, 4547, 4833, 3332, 2464, 3788, 4555, 4884],
 [4559, 2841, 663, 4006, 25, 852, 2948, 3134],
 [4719, 2849, 4869, 4638, 4336, 3819, 1776],
 [2706, 132, 2029, 735, 732, 540, 511],
 [4003, 798, 1647, 1968, 3571],
 [4845, 1509, 2846, 4983, 4685, 3347, 948],
 [4555, 918, 2706, 4003, 3625, 1173],
 [4555, 918, 2706, 4003, 3625, 1173],
 [3421, 3562, 217, 3466, 932, 2506, 4698],
 [3832, 141, 1438, 3017, 2223, 4867],
 [4074, 4492, 882, 4662, 4006, 4395, 1607, 2464],
 [3421, 3562, 217, 3466, 932, 2506, 4698],
 [4845, 1509, 2846, 4983, 4685, 3347, 948],
 [2706, 4074, 132, 2045, 4900, 2680, 3465, 2464],
 [4559, 2841, 663, 4006, 25, 852, 2948, 3134],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [471, 4427, 3812, 798, 4516, 4794, 1919],
 [4292, 511, 705, 3538, 1696, 4176, 2900],
 [3150, 1377, 2943, 762, 3667, 4057],
 [4074, 4492, 882, 4662, 4006, 4395, 1607, 2464],
 [3573, 4511, 4549, 3066, 2031, 2954, 4559],
 [1029, 4276, 4718, 2706, 3300, 2064, 3255],
 [4555, 141, 2215, 2706, 498],
 [1534, 3017, 2912, 1433, 4691, 916],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [429, 1776, 4823, 1811, 2423],
 [1843, 3812, 4613, 2712, 4709, 2052, 3086],
 [2349, 4058, 317, 3422, 478, 4809],
 [3933, 848, 3562, 1895, 4933],
 [2706, 132, 2029, 735, 732, 540, 511],
 [4719, 2849, 4869, 4638, 4336, 3819, 1776],
 [497, 4908, 2659, 4848, 1127, 2938, 4436],
 [1890, 2121, 4984, 400, 2769, 2529],
 [1408, 3758, 2706, 4336, 4062, 4413, 4435],
 [852, 4074, 4492, 2045, 4662, 3086, 1895],
 [1843, 429, 4469, 2015, 4040, 2653],
 [624, 4547, 4833, 3332, 2464, 3788, 4555, 4884],
 [4845, 1509, 2846, 4983, 4685, 3347, 948],
 [4555, 141, 3045, 4038, 3727, 2706, 1173],
 [4555, 2102, 1163, 4590, 2121, 1714, 1198, 1772],
 [4719, 2849, 4869, 4638, 4336, 3819, 1776],
 [3421, 3562, 217, 3466, 932, 2506, 4698],
 [406, 3405, 1444, 3627, 2061, 1890, 1534],
 [2659, 2585, 4900, 66, 4057],
 [471, 4427, 3812, 798, 4516, 4794, 1919],

In [29]:
corpus[1]

'senat pass bipartisan infrastructur packag'

In [30]:
onehot_repr[1]

[2005, 3248, 3496, 2464, 3926]

### Embedding Representation

In [31]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[3426 4469 4823 ...    0    0    0]
 [2005 3248 3496 ...    0    0    0]
 [3421 3562  217 ...    0    0    0]
 ...
 [4559 2841  663 ...    0    0    0]
 [4555  141 3045 ...    0    0    0]
 [4041 4430 1745 ...    0    0    0]]

In [32]:
embedded_docs[1]

array([2005, 3248, 3496, 2464, 3926,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [33]:
embedded_docs[0]

array([3426, 4469, 4823, 4171, 1811,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [34]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [35]:
len(embedded_docs),y.shape

(6000, (6000,))

In [36]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [37]:
X_final.shape,y_final.shape

((6000, 20), (6000,))

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [39]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.8818 - loss: 0.2323 - val_accuracy: 1.0000 - val_loss: 0.0012
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 1.0000 - loss: 6.5619e-04 - val_accuracy: 1.0000 - val_loss: 4.1905e-04
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 1.0000 - loss: 3.2501e-04 - val_accuracy: 1.0000 - val_loss: 2.5171e-04
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 1.0000 - loss: 2.0877e-04 - val_accuracy: 1.0000 - val_loss: 1.7274e-04
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 1.0000 - loss: 1.4900e-04 - val_accuracy: 1.0000 - val_loss: 1.2817e-04
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 1.0000 - loss: 1.1340e-04 - val_accuracy: 1.0000 - val_loss: 1.0005e-04
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 1.0000 - loss: 9.0083e-05 - val_accuracy: 1.0000 - val_loss: 8.0883e-05
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 1.0000 - loss: 7.3770e-05 - val_accuracy: 1.0000 - val_loss: 6.7093e-05
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 1.0000 - loss: 6.1796e-05 - val_accuracy: 1.0000 - val_loss: 5.6759e-05
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 1.0000 - loss: 5.2676e-05 - val_accuracy: 1.0000 - val_loss: 4.8754e-05

### Adding Dropout

In [40]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [41]:
y_pred=model.predict(X_test)

62/62 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

In [42]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [43]:
from sklearn.metrics import confusion_matrix

In [44]:
confusion_matrix(y_test,y_pred)

array([[ 976,    0],
       [1004,    0]])

In [45]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.49292929292929294

In [46]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.49      1.00      0.66       976
           1       0.00      0.00      0.00      1004

    accuracy                           0.49      1980
   macro avg       0.25      0.50      0.33      1980
weighted avg       0.24      0.49      0.33      1980

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))